name: Promote staging to production (quick release)
on:
  push:
    tags:
      - '**-quick'
  workflow_dispatch:

jobs:
  tag:
    runs-on: gha-runners-smartweb
    steps:
      - name: Tag and notify
        uses: IMIO/gha/tag-notify@v3.9.3
        with:
          IMAGE_NAME: 'web/smartweb/mutual'
          IMAGE_TAG: 'staging'
          NEW_IMAGE_TAGS: |
            latest
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.SMARTWEB_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.SMARTWEB_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}
  deploy:
    runs-on: gha-runners-smartweb
    needs: [tag]
    steps:
      - name: Deploy to production and notify
        uses: IMIO/gha/rundeck-notify@v3.9.3
        with:
          RUNDECK_URL: ${{ secrets.RUNDECK_URL }}
          RUNDECK_TOKEN: ${{ secrets.SMARTWEB_RUNDECK_TOKEN }}
          RUNDECK_JOB_ID: ${{ secrets.RUNDECK_DEPLOY_PROD_JOB_ID }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.SMARTWEB_MATTERMOST_WEBHOOK_URL }}

